In [ ]:
Numpy is a librabry for python programming language used for large multidimensional arrays and matrices.
High level mathematical funtions are present for easy operations on data.
Its is a mulidimensional array library

In [2]:
#list are slow compare to numpy arrays
#numpy arrays are faster because of its fixed size and low size memory consumption

In [4]:
#to install numpy
#pip3 install numpy

In [5]:
#loading numpy
import numpy

In [6]:
from numpy import*

In [7]:
#imp method for loading numpy in shortcut form
import numpy as np

Basics

In [8]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [9]:
b  = np.array([
    [9.0, 8.0, 7.0],
    [6.0, 5.0, 4.0]
])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [11]:
#get dimension of array
a.ndim

1

In [12]:
b.ndim

2

In [15]:
#get shape
a.shape

(3,)

In [14]:
b.shape

(2, 3)

In [16]:
#get type
a.dtype

dtype('int32')

In [17]:
#get total_size
a.size

3

In [18]:
#get itemsize
a.itemsize

4

In [21]:
#get total_size_method_I
a.size*a.itemsize

12

In [20]:
#get total_size method_II
a.nbytes

12

Acessing/Changing specific elements, rows, columns etc.,

In [22]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [23]:
#get specific element[r,c]
a[1,5]

13

In [24]:
a[1,-2]

13

In [25]:
#get specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [26]:
#get specific column
a[:,2]

array([ 3, 10])

In [27]:
#get a little more fancy arrays with (start_index, end_index, size)
a[0, 1:6:2]

array([2, 4, 6])

In [28]:
print(a[1, 2:6:2])

[10 12]


In [29]:
#change no
a[1,5]  = 20

In [30]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [31]:
a[:,2] = [1,2]

In [32]:
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [33]:
a[:,2] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [34]:
#3D array
b = np.array([
                [[1,2,3],
                [4,5,6]],
                [[7,8,9],
                [10,11,12]]
])
print(b)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [35]:
#get specific element (work outside in)
b[0,1,1]

5

In [36]:
b[1,:2]

array([[ 7,  8,  9],
       [10, 11, 12]])

Intializing different types of arrays

In [38]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [39]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [40]:
np.ones((4,5), dtype = 'int32')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [41]:
#any other numbers
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [43]:
c = np.full((42,42), 99, dtype = 'int32')

In [44]:
print(c)

[[99 99 99 ... 99 99 99]
 [99 99 99 ... 99 99 99]
 [99 99 99 ... 99 99 99]
 ...
 [99 99 99 ... 99 99 99]
 [99 99 99 ... 99 99 99]
 [99 99 99 ... 99 99 99]]


In [45]:
#any other number full like
np.full_like = (a.shape, 4)

In [46]:
np.random.rand(4,2)

array([[0.84322474, 0.28705333],
       [0.38521289, 0.21656722],
       [0.9261293 , 0.42757822],
       [0.38829299, 0.00394759]])

In [50]:
np.random.rand(7, size = (2,1))

TypeError: rand() got an unexpected keyword argument 'size'

In [52]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [53]:
arr = np.array([1,2,3])
r1 = np.repeat(arr,3)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [62]:
i = np.ones((5,5), dtype = 'int32')
z = np.zeros((3,3))
z[1,1] = 9
i[1:4, 1:4] = z
print(i)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [59]:
print(i)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


Copying an array

In [63]:
a = np.array([1,2,3])
b = a
print(a,b)

[1 2 3] [1 2 3]


In [64]:
b[1] = 31

In [65]:
b

array([ 1, 31,  3])

In [66]:
a

array([ 1, 31,  3])

In [67]:
a = np.array([1,2,3])
b = a.copy()
print(a,b)

[1 2 3] [1 2 3]


In [68]:
b[2] = 21

In [69]:
print(a,b)

[1 2 3] [ 1  2 21]


Mathematics

In [70]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [71]:
a-2

array([-1,  0,  1,  2])

In [72]:
a+12

array([13, 14, 15, 16])

In [73]:
a/12

array([0.08333333, 0.16666667, 0.25      , 0.33333333])

In [74]:
sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [75]:
b = np.array([1,2,3,4])

In [76]:
sin(b)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

Linear Algebra

In [77]:
a = np.ones((2,3))

In [78]:
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [79]:
b = np.full((3,2), 2)

In [80]:
print(b)

[[2 2]
 [2 2]
 [2 2]]


In [82]:
#find determinant
c = np.identity(3)
np.linalg.det(c)

1.0